[package]
name = "statebox/idris-stbx-core"
version = "0.1.0"
authors = []

[dependencies]
"statebox/idris-ct" = { git = "ssh://git@github.com/statebox/idris-ct" }
"vmchale/permutations" = { git = "ssh://git@github.com/marcosh/permutations", tag="elba-tag" }


[targets.lib]
path = "src"
mods =  [ "PetriNet.MultiSet"
        , "PetriNet.PetriNet"
        , "PetriNet.PetriNetMorphisms"
        , "PetriNet.PetriNetsCategory"
        ]
idris_opts = ["-p", "contrib"]
